//! Unbound's remote-control channel, detected by the fact that it speaks TLS at all.
//!
//! 8953 is `unbound-control`, which requires a client certificate and is set up with a self-signed
//! pair generated by `unbound-control-setup`. The definition carried a `NoDistinguishingHandshake`
//! rationale; the handshake is distinguishing, just less so than Docker Swarm's.
//!
//! **This is the weaker of the two TLS probes and the honest ceiling is worth stating.** Unbound's
//! server certificate has no dependable subject — `unbound-control-setup` generates it with a local
//! CN and nothing that names unbound — so unlike `docker_swarm.rs` there is nothing in it to match.
//! What this establishes is "a TLS listener on 8953", combined by the definition with the DNS
//! service on the same host.
//!
//! That is still the property this exists to test. A firewall session helper completing a TCP
//! handshake cannot produce a `ServerHello` and a certificate, so the false positive this whole
//! line of work started from cannot be manufactured here.

use anyhow::Error;
use async_trait::async_trait;

use crate::daemon::utils::app_probe::tls::capture_certificate;
use crate::daemon::utils::app_probe::{AppProbe, AppProbeOutcome, ProbeContext, presence};
use crate::server::ports::r#impl::base::PortType;
use crate::server::services::r#impl::patterns::ClientProbe;

pub struct UnboundControlProbe;

#[async_trait]
impl AppProbe for UnboundControlProbe {
    fn port(&self) -> PortType {
        PortType::new_tcp(8953)
    }

    fn client_probe(&self) -> Option<ClientProbe> {
        Some(ClientProbe::Tls)
    }

    async fn run(&self, ctx: &ProbeContext) -> Result<AppProbeOutcome, Error> {
        let handshake = capture_certificate(ctx, self.port()).await;
        Ok(presence(handshake.spoke_tls()))
    }
}
