//! Where a discovered value came from, and how much that vantage point is worth.
//!
//! One enum for every provenanced field. The probe roster and the derivation set overlap so
//! heavily across `model`, `serial_number`, `mac_address` and `cidr` that per-field enums would be
//! several near-copies of one list — and the two that already existed, `HostNameSource` and
//! `SubnetCidrSource`, had begun to diverge in exactly that way.

use std::fmt;

use serde::{Deserialize, Deserializer, Serialize};
use strum::IntoEnumIterator;
use strum_macros::{EnumDiscriminants, EnumIter, EnumString, IntoStaticStr, VariantNames};
use utoipa::ToSchema;

use crate::server::services::r#impl::patterns::ClientProbe;
use crate::server::shared::types::metadata::{EntityMetadataProvider, HasId, TypeMetadataProvider};
use crate::server::shared::types::{Color, Icon};

/// Whether a person authored this value or a machine emitted it.
///
/// Orthogonal to [`AttributeMethod`]: the same transport carries both — one SNMP session yields
/// `sysLocation` (authored) and `entPhysicalModelName` (emitted).
///
/// The axis exists because binding alone does not order everything, and the case that proves it is
/// SNMP `sysName`. It is a queried fact — we asked the device and it answered — yet it should rank
/// *below* a name a person typed into a controller, which is only reported. An autogenerated
/// `sysName` beating an operator's deliberate name is a plain regression.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, ToSchema)]
pub enum Authorship {
    Machine,
    Human,
}

/// How firmly the exchange binds the claim to the thing the claim is about.
///
/// The tier is declared in exactly one place — [`AttributeSource::method`] and
/// [`ClientProbe::method`] — so a source cannot be filed under two tiers.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Hash,
    Serialize,
    Deserialize,
    ToSchema,
    EnumIter,
    IntoStaticStr,
)]
pub enum AttributeMethod {
    /// Nothing is claimed. The value is present but we cannot say who produced it.
    Unspecified,
    /// No claim exists. We derived the value from something else.
    Inferred,
    /// The subject speaks, but nothing binds the frame to the subject — anything on the link can
    /// emit it.
    Announced,
    /// We know exactly who is speaking, but the speaker is not the subject.
    Reported,
    /// We chose the subject, opened an exchange to its address, and the transport correlated the
    /// answer. True of unauthenticated SNMPv2c as much as of SNMPv3: authentication secures the
    /// channel, not the claim, so it plays no part in the ordering.
    Queried,
    /// Same binding, and the protocol is the subject's own — so the field means what the vendor
    /// says rather than what a generic MIB approximates.
    Native,
    /// A person asserted it in Scanopy.
    Manual,
}

/// How a discovered value reached us.
///
/// Every variant here has something that writes it. Sources with no producer are deliberately
/// absent: a rung the applier can never see is a rung nothing can be tested against, and the tier
/// decision is better made by whoever writes the reader than guessed in advance.
///
/// **Do not derive `Ord`.** A derive compares the variant and then the payload, which would make
/// `Probe(Docker) < Probe(Snmp)` on declaration order alone. Ordering is only ever [`Self::rank`].
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, EnumDiscriminants, ToSchema,
)]
#[strum_discriminants(name(AttributeSourceKind))]
#[strum_discriminants(derive(Hash, EnumIter, EnumString, IntoStaticStr, VariantNames))]
#[serde(tag = "type", content = "probe")]
pub enum AttributeSource {
    /// Provenance unknown: a payload from a daemon predating the rung, a row predating the column,
    /// or a source this binary does not recognise. Below everything, so it never displaces a value
    /// we know the origin of and anything may improve on it.
    #[default]
    #[schema(title = "Unspecified")]
    Unspecified,

    // --- Derivations we perform ourselves. ---
    /// The host's own address, standing in for a name it does not have.
    #[schema(title = "OwnAddress")]
    OwnAddress,
    /// Implied by a matched service definition.
    #[schema(title = "ServiceMatch")]
    ServiceMatch,
    /// A /24 (or /64) convention around an address a neighbour advertised. LLDP carries no netmask
    /// TLV, so the range is our invention rather than the neighbour's claim.
    #[schema(title = "LldpNeighbourAddress")]
    LldpNeighbourAddress,
    /// A manufacturer string synthesised from a numeric CIP vendor ID, because we ship no ODVA
    /// vendor table. Distinct from [`Self::Probe`] over the same transport for the reason the
    /// module doc gives: the variant names what was read, not how it arrived, and `"CIP vendor 1"`
    /// is our own construction rather than anything the device emitted.
    #[schema(title = "CipVendorId")]
    CipVendorId,

    // --- Claims that arrive on the link without a directed exchange. ---
    /// A DNS-SD instance label — the Chromecast `fn=Living Room TV`, typed by a person during
    /// device setup.
    #[schema(title = "DnsSdInstanceName")]
    DnsSdInstanceName,
    /// A chassis ID a neighbour advertised for itself.
    #[schema(title = "LldpChassisId")]
    LldpChassisId,

    // --- Somebody else, about the subject. ---
    /// Reverse DNS. A known speaker that is not the subject.
    #[schema(title = "ReverseDns")]
    ReverseDns,
    /// A router's `ipNetToMediaTable` cache, or a switch's bridge FDB. One variant for both: each
    /// is "a device telling us about a MAC that is not its own", with no basis to rank one above
    /// the other.
    #[schema(title = "ForwardingTable")]
    ForwardingTable,

    // --- Exchanges we direct ourselves. ---
    /// We broadcast an ARP request for a specific address and something replied claiming it.
    #[schema(title = "ArpReply")]
    ArpReply,
    /// The daemon reading its own host: NIC and routing configuration, and its own hostname.
    #[schema(title = "DaemonSelfReport")]
    DaemonSelfReport,

    /// A value the thing emitted about itself, over whatever transport [`ClientProbe`] names.
    #[schema(title = "Probe")]
    Probe(ClientProbe),
    /// A value a person entered into the thing we read it from, carried back over the same
    /// transport: SNMP `sysLocation`, a name set in a controller.
    #[schema(title = "Authored")]
    Authored(ClientProbe),

    /// A person asserted it in Scanopy. Nothing discovery reads displaces it.
    #[schema(title = "Manual")]
    Manual,
}

impl AttributeSource {
    /// Exhaustive, so a new source cannot be added without answering which tier it sits in — the
    /// same property `interface_view_scope()` has, and for the same reason.
    pub fn method(&self) -> AttributeMethod {
        use AttributeMethod as M;
        match self {
            Self::Unspecified => M::Unspecified,

            Self::OwnAddress
            | Self::ServiceMatch
            | Self::LldpNeighbourAddress
            | Self::CipVendorId => M::Inferred,

            Self::DnsSdInstanceName | Self::LldpChassisId => M::Announced,

            Self::ReverseDns | Self::ForwardingTable => M::Reported,

            Self::ArpReply | Self::DaemonSelfReport => M::Queried,

            // Delegated, not because probes are special, but so that adding a probe forces the
            // tier decision at the probe's own definition instead of here — where it would be easy
            // to add a variant and never revisit this match.
            Self::Probe(p) | Self::Authored(p) => p.method(),

            Self::Manual => M::Manual,
        }
    }

    /// Exhaustive, so a new source cannot be added without saying whether a person authored it.
    pub fn authorship(&self) -> Authorship {
        match self {
            Self::Manual | Self::Authored(_) | Self::DnsSdInstanceName => Authorship::Human,
            Self::Unspecified
            | Self::OwnAddress
            | Self::ServiceMatch
            | Self::LldpNeighbourAddress
            | Self::CipVendorId
            | Self::LldpChassisId
            | Self::ReverseDns
            | Self::ForwardingTable
            | Self::ArpReply
            | Self::DaemonSelfReport
            | Self::Probe(_) => Authorship::Machine,
        }
    }

    /// Lexicographic: authorship first, binding second.
    ///
    /// A function rather than `derive(Ord)` on declaration order, because the derive can express
    /// neither the tie nor the authorship dimension.
    pub fn rank(&self) -> u8 {
        use AttributeMethod as M;
        match (self.authorship(), self.method()) {
            (_, M::Unspecified) => 0,

            // Machine-emitted: two sources disagreeing about a fact. Announced and Reported tie —
            // right speaker with no proof it spoke, versus proof and the wrong speaker. Each fails
            // the binding test in a different, incommensurable way, so neither dominates.
            (Authorship::Machine, M::Inferred) => 1,
            (Authorship::Machine, M::Announced | M::Reported) => 2,
            (Authorship::Machine, M::Queried) => 3,
            (Authorship::Machine, M::Native) => 4,

            // Human-authored: the value is not in dispute — both carry the same deliberate intent
            // — only whether the channel carried it faithfully. So a forgeable link-local
            // broadcast does lose to an authenticated read, and the tie above does not apply.
            (Authorship::Human, M::Inferred) => 5,
            (Authorship::Human, M::Announced) => 6,
            (Authorship::Human, M::Reported) => 7,
            (Authorship::Human, M::Queried | M::Native) => 8,

            (_, M::Manual) => 9,
        }
    }

    /// Every source this binary can produce, payload variants expanded.
    ///
    /// The `match` is on the discriminant and exhaustive, so a new payload-bearing variant fails
    /// the build until it says how it enumerates. Used to invert the source→tier table into
    /// [`AttributeMethod`]'s metadata for the UI.
    pub fn all() -> Vec<Self> {
        AttributeSourceKind::iter()
            .flat_map(|kind| match kind {
                AttributeSourceKind::Probe => ClientProbe::iter().map(Self::Probe).collect(),
                AttributeSourceKind::Authored => ClientProbe::iter().map(Self::Authored).collect(),
                AttributeSourceKind::Unspecified => vec![Self::Unspecified],
                AttributeSourceKind::OwnAddress => vec![Self::OwnAddress],
                AttributeSourceKind::ServiceMatch => vec![Self::ServiceMatch],
                AttributeSourceKind::LldpNeighbourAddress => vec![Self::LldpNeighbourAddress],
                AttributeSourceKind::CipVendorId => vec![Self::CipVendorId],
                AttributeSourceKind::DnsSdInstanceName => vec![Self::DnsSdInstanceName],
                AttributeSourceKind::LldpChassisId => vec![Self::LldpChassisId],
                AttributeSourceKind::ReverseDns => vec![Self::ReverseDns],
                AttributeSourceKind::ForwardingTable => vec![Self::ForwardingTable],
                AttributeSourceKind::ArpReply => vec![Self::ArpReply],
                AttributeSourceKind::DaemonSelfReport => vec![Self::DaemonSelfReport],
                AttributeSourceKind::Manual => vec![Self::Manual],
            })
            .collect()
    }
}

/// Human-readable for logs and warnings only — the persisted form is the JSON above, never this.
impl fmt::Display for AttributeSource {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let kind: &'static str = AttributeSourceKind::from(self).into();
        match self {
            Self::Probe(p) | Self::Authored(p) => {
                write!(f, "{kind}({})", <&'static str>::from(*p))
            }
            _ => f.write_str(kind),
        }
    }
}

/// The wire and column shape, read leniently.
///
/// Hand-written rather than derived so that an identifier this binary does not recognise degrades
/// to [`AttributeSource::Unspecified`] instead of failing the row it sits in. `#[serde(other)]`
/// would cover an unknown `type` but not an unknown `probe` inside a known one, and adding a probe
/// is the common case.
///
/// This tolerates exactly two things — an unrecognised variant name and an unrecognised probe name.
/// Malformed JSON is still an error, so it is not a blanket `.ok()`.
#[derive(Deserialize)]
struct WireSource {
    #[serde(rename = "type")]
    kind: String,
    #[serde(default)]
    probe: Option<String>,
}

impl<'de> Deserialize<'de> for AttributeSource {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        use std::str::FromStr;

        let wire = WireSource::deserialize(deserializer)?;

        let Ok(kind) = AttributeSourceKind::from_str(&wire.kind) else {
            tracing::warn!(
                source = %wire.kind,
                "Unrecognized AttributeSource; degrading to Unspecified"
            );
            return Ok(Self::Unspecified);
        };

        // `Probe` and `Authored` are the only kinds carrying one, and a kind that needs a probe
        // without one is as unreadable as an unknown name.
        let probe = || {
            wire.probe
                .as_deref()
                .and_then(|p| ClientProbe::from_str(p).ok())
        };

        Ok(match kind {
            AttributeSourceKind::Probe => match probe() {
                Some(p) => Self::Probe(p),
                None => degrade(&wire),
            },
            AttributeSourceKind::Authored => match probe() {
                Some(p) => Self::Authored(p),
                None => degrade(&wire),
            },
            AttributeSourceKind::Unspecified => Self::Unspecified,
            AttributeSourceKind::OwnAddress => Self::OwnAddress,
            AttributeSourceKind::ServiceMatch => Self::ServiceMatch,
            AttributeSourceKind::LldpNeighbourAddress => Self::LldpNeighbourAddress,
            AttributeSourceKind::CipVendorId => Self::CipVendorId,
            AttributeSourceKind::DnsSdInstanceName => Self::DnsSdInstanceName,
            AttributeSourceKind::LldpChassisId => Self::LldpChassisId,
            AttributeSourceKind::ReverseDns => Self::ReverseDns,
            AttributeSourceKind::ForwardingTable => Self::ForwardingTable,
            AttributeSourceKind::ArpReply => Self::ArpReply,
            AttributeSourceKind::DaemonSelfReport => Self::DaemonSelfReport,
            AttributeSourceKind::Manual => Self::Manual,
        })
    }
}

fn degrade(wire: &WireSource) -> AttributeSource {
    tracing::warn!(
        source = %wire.kind,
        probe = ?wire.probe,
        "Unrecognized probe on an AttributeSource; degrading to Unspecified"
    );
    AttributeSource::Unspecified
}

impl HasId for AttributeMethod {
    fn id(&self) -> &'static str {
        self.into()
    }
}

impl EntityMetadataProvider for AttributeMethod {
    fn color(&self) -> Color {
        match self {
            // The two an operator is being asked to treat with caution.
            Self::Unspecified | Self::Inferred => Color::Indigo,
            Self::Announced | Self::Reported => Color::Gray,
            Self::Queried | Self::Native => Color::Blue,
            Self::Manual => Color::Green,
        }
    }

    fn icon(&self) -> Icon {
        match self {
            Self::Unspecified | Self::Inferred => Icon::CircleQuestionMark,
            Self::Announced | Self::Reported => Icon::Radio,
            Self::Queried | Self::Native => Icon::Network,
            Self::Manual => Icon::User,
        }
    }
}

impl TypeMetadataProvider for AttributeMethod {
    fn name(&self) -> &'static str {
        match self {
            Self::Unspecified => "Unattributed",
            Self::Inferred => "Assumed",
            Self::Announced => "Announced",
            Self::Reported => "Reported by another device",
            Self::Queried => "Read from the device",
            Self::Native => "Read over the device's own protocol",
            Self::Manual => "Entered by a person",
        }
    }

    fn description(&self) -> &'static str {
        match self {
            Self::Unspecified => "Recorded before Scanopy tracked where values came from.",
            Self::Inferred => {
                "Derived from something else rather than read. Good enough to work with, not good enough to assert."
            }
            Self::Announced => {
                "The device broadcast this about itself, on a channel anything on the link could have used."
            }
            Self::Reported => {
                "Another device that manages or observed this one supplied the value."
            }
            Self::Queried => "Scanopy asked this device directly and it answered.",
            Self::Native => {
                "Read over the device's own product protocol, so the value means what its vendor says."
            }
            Self::Manual => "Someone entered this in Scanopy. Discovery never overwrites it.",
        }
    }

    /// The source→tier table, inverted.
    ///
    /// Built by filtering [`AttributeSource::all`] rather than hand-listed, so a source cannot be
    /// filed under the wrong tier here and a new one cannot be forgotten. Entries serialise in the
    /// same shape the API sends, so a consumer compares like with like instead of reconstructing a
    /// key.
    fn metadata(&self) -> serde_json::Value {
        let sources: Vec<AttributeSource> = AttributeSource::all()
            .into_iter()
            .filter(|s| s.method() == *self)
            .collect();
        serde_json::json!({ "sources": sources })
    }
}
