/**
 * Verifies the cancel-reasons.json fixture has the shape the cancel modal
 * depends on. The fixture is generated by the backend's
 * `generate_ui_data_fixtures()` from `CancelReason::TypeMetadataProvider`;
 * if the contract drifts, the modal silently shows the wrong save offers
 * (or none). These tests catch a fixture-shape regression at CI time.
 */
import { describe, it, expect } from 'vitest';
import cancelReasons from '../lib/data/cancel-reasons.json';
import saveOffers from '../lib/data/save-offers.json';

describe('cancel-reasons fixture', () => {
	it('contains all eight canonical CancelReason variants', () => {
		const ids = cancelReasons.map((r) => r.id).sort();
		expect(ids).toEqual([
			'customer_service',
			'low_quality',
			'missing_features',
			'other',
			'switched_service',
			'too_complex',
			'too_expensive',
			'unused'
		]);
	});

	it('every reason has a non-empty human-readable name', () => {
		for (const reason of cancelReasons) {
			expect(reason.name).toBeTruthy();
			expect(typeof reason.name).toBe('string');
		}
	});

	it('every reason has metadata.save_offers as a string array', () => {
		for (const reason of cancelReasons) {
			const offers = (reason.metadata as { save_offers?: string[] } | null | undefined)
				?.save_offers;
			expect(Array.isArray(offers)).toBe(true);
		}
	});

	it('too_expensive routes to pause and discount', () => {
		const reason = cancelReasons.find((r) => r.id === 'too_expensive');
		expect(reason).toBeDefined();
		const offers = (reason!.metadata as { save_offers: string[] }).save_offers;
		expect(offers).toEqual(['pause', 'discount']);
	});

	it('unused routes to pause only', () => {
		const reason = cancelReasons.find((r) => r.id === 'unused');
		expect(reason).toBeDefined();
		const offers = (reason!.metadata as { save_offers: string[] }).save_offers;
		expect(offers).toEqual(['pause']);
	});

	it('reasons without save offers return an empty list', () => {
		const noOffer = [
			'missing_features',
			'switched_service',
			'customer_service',
			'low_quality',
			'too_complex',
			'other'
		];
		for (const id of noOffer) {
			const reason = cancelReasons.find((r) => r.id === id);
			expect(reason, `expected fixture entry for ${id}`).toBeDefined();
			const offers = (reason!.metadata as { save_offers: string[] }).save_offers;
			expect(offers, `${id} should have no save offers`).toEqual([]);
		}
	});

	it('every save_offer id referenced by reasons is defined in save-offers fixture', () => {
		const validOfferIds = new Set(saveOffers.map((o) => o.id));
		for (const reason of cancelReasons) {
			const offers =
				(reason.metadata as { save_offers?: string[] } | null | undefined)?.save_offers ?? [];
			for (const offerId of offers) {
				expect(validOfferIds.has(offerId), `unknown save offer "${offerId}" on ${reason.id}`).toBe(
					true
				);
			}
		}
	});
});

describe('save-offers fixture', () => {
	it('contains pause, discount, downgrade', () => {
		const ids = saveOffers.map((o) => o.id).sort();
		expect(ids).toEqual(['discount', 'downgrade', 'pause']);
	});

	it('every offer has a non-empty name and description', () => {
		for (const offer of saveOffers) {
			expect(offer.name).toBeTruthy();
			expect(offer.description).toBeTruthy();
		}
	});
});
